serve: true
permalink: pretty
collections:
  code:
    output: true
    # permalink: pretty
  # art:
  #   output: true
  #   permalink: pretty
  # music:
  #   output: true
  #   permalink: pretty
destination: docs
